### ISSUE TITLE
Newest version of Windows Notepad has support for Unix line breaks

### ISSUE THREAD

**Issue by ghost** [pinobatch/nrom-template#1]
```
IF THIS FILE HAS NO LINE BREAKS: View it in a web browser.
Windows Notepad is a very popular text editor that comes with the Windows operating system, but it doesn't recognize line breaks in text files made on Linux or any other UNIX-like operating system.
Text files with UNIX line breaks display correctly in WordPad, Notepad++, Programmer's Notepad, Gedit, or a web browser, just not in Windows Notepad.
```
Should be removed from the README once the next Windows feature update (RS5) lands.

See: <https://blogs.msdn.microsoft.com/commandline/2018/05/08/extended-eol-in-notepad/>

**Comment by pinobatch** [comment]
I don't expect Microsoft to backport Notepad RS5 to Windows 7 or Windows 8.1. Nor do I see much point in bugging users of those operating systems to pay for an upgrade to Windows 10 until January 10, 2023, when Microsoft plans to terminate security updates for Windows 8.1. Many purposely use Windows 7 because it shares less personal information with Microsoft than Windows 10 and has had smaller, less frequent service packs.

Is there a way to close an issue such that GitHub will automatically reopen it in a few years?

**Comment by pinobatch** [comment]
As for when to remove "forthcoming" added in c58fa4af42c78cb888328002980ba14c6a689b13:

 ["Windows 10 Redstone 5 news, rumors and release date" by Matt Hanson][1] speculates an October 2018 release date for the Redstone 5 service pack. ["Microsoft Finally Distributing Redstone 5 ISOs" by Nathaniel Mott][2] reports that Windows 10 licensees on the Insider Program slow ring can download a disk image of RS5 as of August 2018.

[1]: https://www.techradar.com/news/windows-10-redstone-5-rumors-release-date
[2]: https://www.tomshardware.com/news/microsoft-windows-10-redstone-5-release,37541.html

**Comment by pinobatch** [comment]
["Microsoft announces Windows 10 October 2018 Update" by Emil Protalinski](https://venturebeat.com/2018/08/31/microsoft-announces-windows-10-october-2018-update/) confirms that Microsoft has scheduled this update for sometime before the end of October.

**Comment by ghost** [comment]
This update ended up rolling out around late March (https://www.ghacks.net/2019/03/21/windows-10-1809-full-rollout-begins/), but now that it has been released and resolved I am closing this issue.
